# Generated by Django 3.0.4 on 2020-03-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200331_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.PositiveSmallIntegerField(max_length=10),
        ),
    ]
