# Generated by Django 3.0.4 on 2020-03-28 20:00

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=26)),
                ('description', models.CharField(max_length=620)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100)),
                ('sub_category', models.CharField(default='', max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('short_description', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('new_price', models.PositiveIntegerField(blank=True, null=True)),
                ('pub_date', models.DateField()),
                ('warranty', models.CharField(default='No', max_length=20)),
                ('replacement', models.CharField(default='No', max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('url', models.CharField(default='kmz2ooPe0ZaM3RJHkUZ1SMZZFWdWe9Yh', max_length=32)),
                ('product_img1', models.ImageField(default='shop/img/default.png', upload_to=shop.models.get_upload_path)),
                ('product_img2', models.ImageField(blank=True, default='shop/img/default.png', upload_to=shop.models.get_upload_path)),
                ('product_img3', models.ImageField(blank=True, default='shop/img/default.png', upload_to=shop.models.get_upload_path)),
                ('product_img4', models.ImageField(blank=True, default='shop/img/default.png', upload_to=shop.models.get_upload_path)),
                ('product_img5', models.ImageField(blank=True, default='shop/img/default.png', upload_to=shop.models.get_upload_path)),
                ('product_img6', models.ImageField(blank=True, default='shop/img/default.png', upload_to=shop.models.get_upload_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='shop.Category')),
            ],
        ),
    ]
