# Generated by Django 3.0.4 on 2020-03-28 20:13

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200329_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img1',
            field=models.ImageField(default='shop/img/product/default.png', upload_to=shop.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img2',
            field=models.ImageField(blank=True, default='shop/img/product/default.png', upload_to=shop.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img3',
            field=models.ImageField(blank=True, default='shop/img/product/default.png', upload_to=shop.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img4',
            field=models.ImageField(blank=True, default='shop/img/product/default.png', upload_to=shop.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img5',
            field=models.ImageField(blank=True, default='shop/img/product/default.png', upload_to=shop.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img6',
            field=models.ImageField(blank=True, default='shop/img/product/default.png', upload_to=shop.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='dI7BcGkgehtka7siCT76T9SL1ofCd3Ja', max_length=32),
        ),
    ]
