# Generated by Django 3.0.4 on 2020-03-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200329_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='img',
            field=models.ImageField(default=1, upload_to='shop/img/slider/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='YxGZe3R1BjJtxL9sh5pjjZpJ6nm3sZRu', max_length=32),
        ),
    ]
