# Generated by Django 3.0.4 on 2020-03-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200329_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='IoVLpeM6G2YuVNnzOptVZVbMvFnBEq2i', max_length=32),
        ),
    ]
