# Generated by Django 3.0.4 on 2020-03-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200329_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='yO2w5RFBpUfiYoZllQIegXyKX5gqSEod', max_length=32),
        ),
    ]
