# Generated by Django 3.0.4 on 2020-03-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200330_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='gqoKmWgGFZX1yA2x1VoHHdAnywupwReX', max_length=32),
        ),
    ]
