# Generated by Django 3.0.4 on 2020-03-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200330_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='r3HsrHsKEZWZmuUUcdZK4y7R7L7Tg2PY', max_length=32),
        ),
    ]
