# Generated by Django 3.0.4 on 2020-03-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200330_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='qShf3hs2Ie5tcHcmSKCiqRsxrsO2r8ig', max_length=32),
        ),
    ]
