# Generated by Django 3.0.4 on 2020-03-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200330_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='rxFSOY7lc9Cm5cMQoo2Op1H7C0a9RVf8', max_length=32),
        ),
    ]
