# Generated by Django 3.0.4 on 2020-03-29 22:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200330_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='F8L6iqhwYjMgBJUQJLgTZQ36IAi439TL', max_length=32),
        ),
    ]
