# Generated by Django 3.0.4 on 2020-03-29 22:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200330_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='bQCMLhrahASbqR3EfJbLzunpvxjXu12X', max_length=32),
        ),
    ]
