# Generated by Django 3.0.4 on 2020-03-29 22:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200330_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='D5AXsduPTrwB76Mrwk8R1Wng0MnzjRlw', max_length=32),
        ),
    ]
