# Generated by Django 3.0.4 on 2020-03-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200330_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='dF2fuzK06MbnC48j9oYhVlBnfoj5PEoy', max_length=32),
        ),
    ]
