# Generated by Django 3.0.4 on 2020-03-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200330_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='5BfI7JNhEwCzHl402xKJTyHL7mdmbkuH', max_length=32),
        ),
    ]
