# Generated by Django 3.0.4 on 2020-03-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200330_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='gogH7A0fcnZhvaLnUHYqesDxHfwFJtkC', max_length=32),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
