# Generated by Django 3.0.4 on 2020-03-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20200330_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='fUd4bhBnfhcfCFiDwkOE40Ssm9lDkBvp', max_length=32),
        ),
    ]
