# Generated by Django 3.0.4 on 2020-03-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20200330_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='zA0bfhehKxEkWshs3mKexx1bDz3CnX7n', max_length=32),
        ),
    ]
