# Generated by Django 3.0.4 on 2020-03-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20200331_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='Q5wD42sSYc4cPivknQX5k6eAgJgbp2RA', max_length=32),
        ),
    ]
