# Generated by Django 3.0.4 on 2020-03-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20200331_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='xAcWvjoqoTx6txABlRmVGNF3eopHzXtp', max_length=32),
        ),
    ]
