# Generated by Django 3.0.4 on 2020-03-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20200331_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='ya23Q6Td5Svj8pZcckpk8AnNy92Zwtbn', max_length=32),
        ),
    ]
