# Generated by Django 3.0.4 on 2020-03-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20200331_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(default='RLJyoKmXEQoqVTDSLyHQsRwGJtz1MiLN', max_length=32),
        ),
    ]
